name: roqtrade
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  http: ^1.5.0
  intl: ^0.20.2
  lottie: ^3.2.0
  percent_indicator: ^4.2.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_easyloading: ^3.0.5
  overlay_support: ^2.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true


  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/roqtrade.png"
